# Generated by Django 5.0.1 on 2024-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_city_customuser_country_customuser_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
